// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ntv_dump.proto

#ifndef PROTOBUF_ntv_5fdump_2eproto__INCLUDED
#define PROTOBUF_ntv_5fdump_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ntv_5fdump_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsntv_dump_funcsImpl();
void InitDefaultsntv_dump_funcs();
void InitDefaultsntv_dump_FuncTableEntry_DoNotUseImpl();
void InitDefaultsntv_dump_FuncTableEntry_DoNotUse();
void InitDefaultsntv_dump_ScriptFuncsEntry_DoNotUseImpl();
void InitDefaultsntv_dump_ScriptFuncsEntry_DoNotUse();
void InitDefaultsntv_dumpImpl();
void InitDefaultsntv_dump();
inline void InitDefaults() {
  InitDefaultsntv_dump_funcs();
  InitDefaultsntv_dump_FuncTableEntry_DoNotUse();
  InitDefaultsntv_dump_ScriptFuncsEntry_DoNotUse();
  InitDefaultsntv_dump();
}
}  // namespace protobuf_ntv_5fdump_2eproto
namespace nob {
class ntv_dump;
class ntv_dumpDefaultTypeInternal;
extern ntv_dumpDefaultTypeInternal _ntv_dump_default_instance_;
class ntv_dump_FuncTableEntry_DoNotUse;
class ntv_dump_FuncTableEntry_DoNotUseDefaultTypeInternal;
extern ntv_dump_FuncTableEntry_DoNotUseDefaultTypeInternal _ntv_dump_FuncTableEntry_DoNotUse_default_instance_;
class ntv_dump_ScriptFuncsEntry_DoNotUse;
class ntv_dump_ScriptFuncsEntry_DoNotUseDefaultTypeInternal;
extern ntv_dump_ScriptFuncsEntry_DoNotUseDefaultTypeInternal _ntv_dump_ScriptFuncsEntry_DoNotUse_default_instance_;
class ntv_dump_funcs;
class ntv_dump_funcsDefaultTypeInternal;
extern ntv_dump_funcsDefaultTypeInternal _ntv_dump_funcs_default_instance_;
}  // namespace nob
namespace nob {

// ===================================================================

class ntv_dump_funcs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nob.ntv_dump.funcs) */ {
 public:
  ntv_dump_funcs();
  virtual ~ntv_dump_funcs();

  ntv_dump_funcs(const ntv_dump_funcs& from);

  inline ntv_dump_funcs& operator=(const ntv_dump_funcs& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ntv_dump_funcs(ntv_dump_funcs&& from) noexcept
    : ntv_dump_funcs() {
    *this = ::std::move(from);
  }

  inline ntv_dump_funcs& operator=(ntv_dump_funcs&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ntv_dump_funcs& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ntv_dump_funcs* internal_default_instance() {
    return reinterpret_cast<const ntv_dump_funcs*>(
               &_ntv_dump_funcs_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ntv_dump_funcs* other);
  friend void swap(ntv_dump_funcs& a, ntv_dump_funcs& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ntv_dump_funcs* New() const PROTOBUF_FINAL { return New(NULL); }

  ntv_dump_funcs* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ntv_dump_funcs& from);
  void MergeFrom(const ntv_dump_funcs& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ntv_dump_funcs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 addr = 1;
  int addr_size() const;
  void clear_addr();
  static const int kAddrFieldNumber = 1;
  ::google::protobuf::uint64 addr(int index) const;
  void set_addr(int index, ::google::protobuf::uint64 value);
  void add_addr(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      addr() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_addr();

  // @@protoc_insertion_point(class_scope:nob.ntv_dump.funcs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > addr_;
  mutable int _addr_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_ntv_5fdump_2eproto::TableStruct;
  friend void ::protobuf_ntv_5fdump_2eproto::InitDefaultsntv_dump_funcsImpl();
};
// -------------------------------------------------------------------

class ntv_dump_FuncTableEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ntv_dump_FuncTableEntry_DoNotUse, 
    ::google::protobuf::uint64, ::google::protobuf::uint64,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<ntv_dump_FuncTableEntry_DoNotUse, 
    ::google::protobuf::uint64, ::google::protobuf::uint64,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
    0 > SuperType;
  ntv_dump_FuncTableEntry_DoNotUse();
  ntv_dump_FuncTableEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ntv_dump_FuncTableEntry_DoNotUse& other);
  static const ntv_dump_FuncTableEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ntv_dump_FuncTableEntry_DoNotUse*>(&_ntv_dump_FuncTableEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ntv_dump_ScriptFuncsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ntv_dump_ScriptFuncsEntry_DoNotUse, 
    ::std::string, ::nob::ntv_dump_funcs,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<ntv_dump_ScriptFuncsEntry_DoNotUse, 
    ::std::string, ::nob::ntv_dump_funcs,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  ntv_dump_ScriptFuncsEntry_DoNotUse();
  ntv_dump_ScriptFuncsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ntv_dump_ScriptFuncsEntry_DoNotUse& other);
  static const ntv_dump_ScriptFuncsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ntv_dump_ScriptFuncsEntry_DoNotUse*>(&_ntv_dump_ScriptFuncsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ntv_dump : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nob.ntv_dump) */ {
 public:
  ntv_dump();
  virtual ~ntv_dump();

  ntv_dump(const ntv_dump& from);

  inline ntv_dump& operator=(const ntv_dump& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ntv_dump(ntv_dump&& from) noexcept
    : ntv_dump() {
    *this = ::std::move(from);
  }

  inline ntv_dump& operator=(ntv_dump&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ntv_dump& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ntv_dump* internal_default_instance() {
    return reinterpret_cast<const ntv_dump*>(
               &_ntv_dump_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ntv_dump* other);
  friend void swap(ntv_dump& a, ntv_dump& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ntv_dump* New() const PROTOBUF_FINAL { return New(NULL); }

  ntv_dump* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ntv_dump& from);
  void MergeFrom(const ntv_dump& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ntv_dump* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ntv_dump_funcs funcs;

  // accessors -------------------------------------------------------

  // map<uint64, uint64> func_table = 1;
  int func_table_size() const;
  void clear_func_table();
  static const int kFuncTableFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
      func_table() const;
  ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
      mutable_func_table();

  // map<string, .nob.ntv_dump.funcs> script_funcs = 2;
  int script_funcs_size() const;
  void clear_script_funcs();
  static const int kScriptFuncsFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::nob::ntv_dump_funcs >&
      script_funcs() const;
  ::google::protobuf::Map< ::std::string, ::nob::ntv_dump_funcs >*
      mutable_script_funcs();

  // @@protoc_insertion_point(class_scope:nob.ntv_dump)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      ntv_dump_FuncTableEntry_DoNotUse,
      ::google::protobuf::uint64, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > func_table_;
  ::google::protobuf::internal::MapField<
      ntv_dump_ScriptFuncsEntry_DoNotUse,
      ::std::string, ::nob::ntv_dump_funcs,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > script_funcs_;
  mutable int _cached_size_;
  friend struct ::protobuf_ntv_5fdump_2eproto::TableStruct;
  friend void ::protobuf_ntv_5fdump_2eproto::InitDefaultsntv_dumpImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ntv_dump_funcs

// repeated uint64 addr = 1;
inline int ntv_dump_funcs::addr_size() const {
  return addr_.size();
}
inline void ntv_dump_funcs::clear_addr() {
  addr_.Clear();
}
inline ::google::protobuf::uint64 ntv_dump_funcs::addr(int index) const {
  // @@protoc_insertion_point(field_get:nob.ntv_dump.funcs.addr)
  return addr_.Get(index);
}
inline void ntv_dump_funcs::set_addr(int index, ::google::protobuf::uint64 value) {
  addr_.Set(index, value);
  // @@protoc_insertion_point(field_set:nob.ntv_dump.funcs.addr)
}
inline void ntv_dump_funcs::add_addr(::google::protobuf::uint64 value) {
  addr_.Add(value);
  // @@protoc_insertion_point(field_add:nob.ntv_dump.funcs.addr)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ntv_dump_funcs::addr() const {
  // @@protoc_insertion_point(field_list:nob.ntv_dump.funcs.addr)
  return addr_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ntv_dump_funcs::mutable_addr() {
  // @@protoc_insertion_point(field_mutable_list:nob.ntv_dump.funcs.addr)
  return &addr_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ntv_dump

// map<uint64, uint64> func_table = 1;
inline int ntv_dump::func_table_size() const {
  return func_table_.size();
}
inline void ntv_dump::clear_func_table() {
  func_table_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
ntv_dump::func_table() const {
  // @@protoc_insertion_point(field_map:nob.ntv_dump.func_table)
  return func_table_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
ntv_dump::mutable_func_table() {
  // @@protoc_insertion_point(field_mutable_map:nob.ntv_dump.func_table)
  return func_table_.MutableMap();
}

// map<string, .nob.ntv_dump.funcs> script_funcs = 2;
inline int ntv_dump::script_funcs_size() const {
  return script_funcs_.size();
}
inline void ntv_dump::clear_script_funcs() {
  script_funcs_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::nob::ntv_dump_funcs >&
ntv_dump::script_funcs() const {
  // @@protoc_insertion_point(field_map:nob.ntv_dump.script_funcs)
  return script_funcs_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::nob::ntv_dump_funcs >*
ntv_dump::mutable_script_funcs() {
  // @@protoc_insertion_point(field_mutable_map:nob.ntv_dump.script_funcs)
  return script_funcs_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace nob

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ntv_5fdump_2eproto__INCLUDED
